# Generated by Django 4.2.7 on 2025-08-14 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsummary",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ta", "Tamil"), ("si", "Sinhala")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="documentsummary",
            name="multilingual_summaries",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="legalterm",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ta", "Tamil"), ("si", "Sinhala")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="legalterm",
            name="multilingual_definitions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="legalterm",
            name="multilingual_explanations",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="UserLanguagePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("ta", "Tamil"), ("si", "Sinhala")],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "fallback_language",
                    models.CharField(
                        choices=[("en", "English"), ("ta", "Tamil"), ("si", "Sinhala")],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("auto_translate", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "preferred_language")},
            },
        ),
    ]
